import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "primary": "#2b4bb9",
        "outline": "#737686",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed": "#d5e3fc",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#0d1c2e",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed-variant": "#173bab",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-tint": "#3755c3",
        "primary-fixed-dim": "#b8c4ff",
        "on-tertiary-container": "#bdffdb",
        "tertiary": "#006242",
        "outline-variant": "#c3c6d7",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#dde1ff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#001453",
        "secondary-container": "#d5e3fc",
        "surface-bright": "#f8f9ff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#b9c7df",
        "inverse-primary": "#b8c4ff",
        "on-tertiary-fixed-variant": "#005236",
        "secondary": "#515f74",
        "on-secondary-fixed-variant": "#3a485b",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-surface-variant": "#434655",
        "tertiary-container": "#007d55",
        "on-primary-container": "#efefff",
        "on-background": "#0b1c30",
        "on-tertiary-fixed": "#002113",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
        "on-secondary-container": "#57657a",
        "primary-container": "#4865d3"
      },
    },
  },
  plugins: [],
};
export default config;