export const currencies = [
  { symbol: "₹", code: "INR", name: "Indian Rupee" },
  { symbol: "$", code: "USD", name: "US Dollar" },
  { symbol: "€", code: "EUR", name: "Euro" },
  { symbol: "£", code: "GBP", name: "British Pound" },
  { symbol: "A$", code: "AUD", name: "Australian Dollar" },
  { symbol: "C$", code: "CAD", name: "Canadian Dollar" },
  { symbol: "¥", code: "JPY", name: "Japanese Yen" },
  { symbol: "¥", code: "CNY", name: "Chinese Yuan" },
  { symbol: "CHF", code: "CHF", name: "Swiss Franc" },
  { symbol: "₩", code: "KRW", name: "South Korean Won" },
  { symbol: "SGD", code: "SGD", name: "Singapore Dollar" },
  { symbol: "HK$", code: "HKD", name: "Hong Kong Dollar" },
  { symbol: "NZ$", code: "NZD", name: "New Zealand Dollar" },
  { symbol: "SEK", code: "SEK", name: "Swedish Krona" },
  { symbol: "NOK", code: "NOK", name: "Norwegian Krone" },
  { symbol: "DKK", code: "DKK", name: "Danish Krone" },
  { symbol: "₽", code: "RUB", name: "Russian Ruble" },
  { symbol: "R$", code: "BRL", name: "Brazilian Real" },
  { symbol: "R", code: "ZAR", name: "South African Rand" },
  { symbol: "₺", code: "TRY", name: "Turkish Lira" },
  { symbol: "AED", code: "AED", name: "UAE Dirham" },
  { symbol: "SAR", code: "SAR", name: "Saudi Riyal" },
];